const Emojis = {
  SUCCESS: '✅',
  ERROR: '❌',
  WARNING: '⚠️',
  INFO: 'ℹ️',
  LOADING: '⏳',
  SHIELD: '🛡️',
  LOCK: '🔒',
  UNLOCK: '🔓',
  BAN: '🔨',
  KICK: '👢',
  TIMEOUT: '⏰',
  WARN: '⚠️',
  TICKET: '🎫',
  VOICE: '🔊',
  SETTINGS: '⚙️',
  STAR: '⭐',
  CROWN: '👑',
  MEMBER: '👤',
  MEMBERS: '👥',
  CHANNEL: '#️⃣',
  ROLE: '🏷️',
  LOG: '📋',
  TRASH: '🗑️',
  EDIT: '✏️',
  LINK: '🔗',
  SECURITY: '🔐',
  WELCOME: '👋',
  LEVEL: '📊',
  SUGGESTION: '💡',
  GIVEAWAY: '🎉',
};

module.exports = Emojis;
