const Limits = {
  SPAM_MESSAGE_LIMIT: 5,
  SPAM_TIME_WINDOW: 5000,
  RAID_JOIN_LIMIT: 10,
  RAID_JOIN_WINDOW: 10000,
  MENTION_LIMIT: 8,
  CAPS_THRESHOLD: 0.7,
  CAPS_MIN_LENGTH: 10,
  EMOJI_SPAM_LIMIT: 10,
  DUPLICATE_MESSAGE_LIMIT: 3,
  DUPLICATE_TIME_WINDOW: 30000,

  DEFAULT_COMMAND_COOLDOWN: 3000,
  SETUP_COOLDOWN: 60000,

  TEMP_VOICE_MAX_ROOMS_PER_GUILD: 50,
  TEMP_VOICE_CLEANUP_INTERVAL: 60000,

  MAX_OPEN_TICKETS_PER_USER: 3,
  TRANSCRIPT_MAX_MESSAGES: 500,

  MAX_PURGE_MESSAGES: 100,
  WARN_EXPIRY_DAYS: 30,

  XP_PER_MESSAGE_MIN: 15,
  XP_PER_MESSAGE_MAX: 25,
  XP_COOLDOWN: 60000,

  RISK_LOW: 25,
  RISK_MEDIUM: 50,
  RISK_HIGH: 75,
  RISK_CRITICAL: 90,
};

module.exports = Limits;
